### ISSUE TITLE
Cannot jump into templates

### ISSUE THREAD

**Issue by alanlalonde** [lamabiker/atom-ember-cli-helper#37]
Steps to reproduce:

1. Position cursor on name of an Ember template.
2. CTRL + ALT + Enter
3. Uncaught error as detailed below.

**Atom**: 1.19.7 ia32
**Electron**: 1.6.9
**OS**: Microsoft Windows 7 Professional 
**Thrown From**: [ember-cli-helper](https://github.com/apprentus/atom-ember-cli-helper) package 0.9.0

### Stack Trace

Uncaught TypeError: Cannot read property '18' of undefined

```
At /C:/Users/user/.atom/packages/ember-cli-helper/lib/ember-cli-helper-view.coffee:247

TypeError: Cannot read property '18' of undefined
    at EmberCliHelperView.module.exports.EmberCliHelperView.openComponent (/packages/ember-cli-helper/lib/ember-cli-helper-view.coffee:177:32)
    at /packages/ember-cli-helper/lib/ember-cli-helper-view.coffee:31:46)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.19.7/resources/app/src/command-registry.js:265:35)
    at ~/AppData/Local/atom/app-1.19.7/resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.19.7/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.19.7/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.19.7/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (~/AppData/Local/atom/app-1.19.7/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -4:10.8.0 ember-cli-helper:open-component (input.hidden-input)
     -0:13.2.0 intentions:highlight (input.hidden-input)
     -0:08.6.0 ember-cli-helper:open-component (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
atom-bootstrap3 1.2.12 
atom-handlebars 1.3.0 
autoclose-html 0.23.0 
busy-signal 1.4.3 
ember-cli-helper 0.9.0 
ember-snippets 2.1.2 
es6-javascript 1.0.0 
file-icons 2.1.11 
git-plus 7.9.3 
highlight-selected 0.13.1 
intentions 1.1.5 
less-than-slash 0.17.0 
linter 2.2.0 
linter-csslint 2.0.0 
linter-eslint 8.2.1 
linter-handlebars 2.5.0 
linter-ui-default 1.6.8 
merge-conflicts 1.4.5 
minimap 4.29.6 
minimap-highlight-selected 4.6.1 
```

**Comment by lamabiker** [comment]
Hi @alanlalonde, can you confirm this issue has been fixed with the latest release? Thanks!

**Comment by lamabiker** [comment]
I'm closing this due to inactivity, feel free to reopen if need be.
